services:
  postgres:
    image: postgres:16-alpine
    container_name: freestyle-db
    environment:
      POSTGRES_USER: freestyle
      POSTGRES_PASSWORD: freestyle123
      POSTGRES_DB: freestyle
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: freestyle-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  pgdata:
