export const countries = [
  { code: "AR", name: "Argentina", flagEmoji: "🇦🇷" },
  { code: "ES", name: "España", flagEmoji: "🇪🇸" },
  { code: "MX", name: "México", flagEmoji: "🇲🇽" },
  { code: "CL", name: "Chile", flagEmoji: "🇨🇱" },
  { code: "PE", name: "Perú", flagEmoji: "🇵🇪" },
  { code: "CO", name: "Colombia", flagEmoji: "🇨🇴" },
  { code: "VE", name: "Venezuela", flagEmoji: "🇻🇪" },
  { code: "DO", name: "República Dominicana", flagEmoji: "🇩🇴" },
  { code: "UY", name: "Uruguay", flagEmoji: "🇺🇾" },
  { code: "PA", name: "Panamá", flagEmoji: "🇵🇦" },
  { code: "CR", name: "Costa Rica", flagEmoji: "🇨🇷" },
  { code: "GT", name: "Guatemala", flagEmoji: "🇬🇹" },
  { code: "PR", name: "Puerto Rico", flagEmoji: "🇵🇷" },
] as const;

export const freestylers = [
  { alias: "Wos", slug: "wos", countryCode: "AR" },
  { alias: "Acru", slug: "acru", countryCode: "AR" },
  { alias: "Duki", slug: "duki", countryCode: "AR" },
  { alias: "Ecko", slug: "ecko", countryCode: "AR" },
  { alias: "Lit Killah", slug: "lit-killah", countryCode: "AR" },
  { alias: "RepliK", slug: "replik", countryCode: "AR" },
  { alias: "Trueno", slug: "trueno", countryCode: "AR" },
  { alias: "Papo", slug: "papo", countryCode: "AR" },
  { alias: "Stuart", slug: "stuart", countryCode: "AR" },
  { alias: "Klan", slug: "klan", countryCode: "AR" },
  { alias: "Dtoke", slug: "dtoke", countryCode: "AR" },
  { alias: "Mecha", slug: "mecha", countryCode: "AR" },
  { alias: "CTZ", slug: "ctz", countryCode: "AR" },
  { alias: "Dani", slug: "dani", countryCode: "AR" },
  { alias: "Exe", slug: "exe", countryCode: "AR" },
  { alias: "Kodigo", slug: "kodigo", countryCode: "AR" },
  { alias: "MP", slug: "mp", countryCode: "AR" },
  { alias: "Nacho", slug: "nacho", countryCode: "AR" },
  { alias: "Larrix", slug: "larrix", countryCode: "AR" },
  { alias: "Chuty", slug: "chuty", countryCode: "ES" },
  { alias: "Gazir", slug: "gazir", countryCode: "ES" },
  { alias: "Skone", slug: "skone", countryCode: "ES" },
  { alias: "Bnet", slug: "bnet", countryCode: "ES" },
  { alias: "Blon", slug: "blon", countryCode: "ES" },
  { alias: "Sweet Pain", slug: "sweet-pain", countryCode: "ES" },
  { alias: "Zasko", slug: "zasko", countryCode: "ES" },
  { alias: "Alek", slug: "alek", countryCode: "ES" },
  { alias: "Arkano", slug: "arkano", countryCode: "ES" },
  { alias: "Barón", slug: "baron", countryCode: "ES" },
  { alias: "Mnak", slug: "mnak", countryCode: "ES" },
  { alias: "Aczino", slug: "aczino", countryCode: "MX" },
  { alias: "Rapder", slug: "rapder", countryCode: "MX" },
  { alias: "Jony Beltrán", slug: "jony-beltran", countryCode: "MX" },
  { alias: "RC", slug: "rc", countryCode: "MX" },
  { alias: "Lobo Estepario", slug: "lobo-estepario", countryCode: "MX" },
  { alias: "Azuky", slug: "azuky", countryCode: "MX" },
  { alias: "Acertijo", slug: "acertijo", countryCode: "CL" },
  { alias: "Metalingüística", slug: "metalinguistica", countryCode: "CL" },
  { alias: "Nitro", slug: "nitro", countryCode: "CL" },
  { alias: "Teorema", slug: "teorema", countryCode: "CL" },
  { alias: "Kaiser", slug: "kaiser", countryCode: "CL" },
  { alias: "El Menor", slug: "el-menor", countryCode: "CL" },
  { alias: "Jokker", slug: "jokker", countryCode: "CL" },
  { alias: "Drose", slug: "drose", countryCode: "CL" },
  { alias: "Pepe Grillo", slug: "pepe-grillo", countryCode: "CL" },
  { alias: "Jaze", slug: "jaze", countryCode: "PE" },
  { alias: "Nekroos", slug: "nekroos", countryCode: "PE" },
  { alias: "Stick", slug: "stick", countryCode: "PE" },
  { alias: "KG", slug: "kg", countryCode: "PE" },
  { alias: "Valles-T", slug: "valles-t", countryCode: "CO" },
  { alias: "Marithea", slug: "marithea", countryCode: "CO" },
  { alias: "Filósofo", slug: "filosofo", countryCode: "CO" },
  { alias: "Lokillo", slug: "lokillo", countryCode: "CO" },
] as const;
