export const STYLE_TAGS = [
  { slug: "punchline", name: "Punchline", description: "Impacto directo, remates y golpes verbales." },
  { slug: "metricas", name: "Métricas", description: "Estructuras, patrones y construcción técnica." },
  { slug: "flow", name: "Flow", description: "Cadencia, musicalidad y adaptación a la base." },
  { slug: "doble-tempo", name: "Doble tempo", description: "Velocidad y claridad en patrones acelerados." },
  { slug: "respuesta", name: "Respuesta", description: "Réplicas inmediatas y uso de lo dicho por el rival." },
  { slug: "ingenio", name: "Ingenio", description: "Conceptos, asociaciones y recursos inesperados." },
  { slug: "puesta-escena", name: "Puesta en escena", description: "Presencia, interpretación y dominio del escenario." },
  { slug: "libre", name: "Libre", description: "Improvisación orgánica con poca dependencia de estructuras fijas." },
] as const;

export type StyleSlug = typeof STYLE_TAGS[number]["slug"];

export const VERIFIED_STYLES: Record<string, [StyleSlug, StyleSlug]> = {
  Wos: ["flow", "puesta-escena"],
  Acru: ["metricas", "flow"],
  Duki: ["flow", "puesta-escena"],
  Ecko: ["punchline", "flow"],
  "Lit Killah": ["flow", "doble-tempo"],
  RepliK: ["metricas", "ingenio"],
  Trueno: ["flow", "puesta-escena"],
  Acertijo: ["punchline", "respuesta"],
  Metalingüística: ["metricas", "ingenio"],
  Papo: ["punchline", "respuesta"],
  Stuart: ["metricas", "flow"],
  Klan: ["libre", "punchline"],
  Dtoke: ["punchline", "puesta-escena"],
  Mecha: ["punchline", "doble-tempo"],
  Nacho: ["metricas", "punchline"],
  Larrix: ["punchline", "respuesta"],
  Chuty: ["punchline", "metricas"],
  Gazir: ["ingenio", "respuesta"],
  Skone: ["puesta-escena", "respuesta"],
  Bnet: ["libre", "metricas"],
  Blon: ["punchline", "respuesta"],
  "Sweet Pain": ["metricas", "punchline"],
  Zasko: ["metricas", "doble-tempo"],
  Aczino: ["respuesta", "punchline"],
  Rapder: ["punchline", "puesta-escena"],
  "Jony Beltrán": ["flow", "puesta-escena"],
  RC: ["punchline", "respuesta"],
  "Lobo Estepario": ["punchline", "flow"],
  Nitro: ["punchline", "puesta-escena"],
  Teorema: ["ingenio", "libre"],
  Kaiser: ["punchline", "respuesta"],
  "El Menor": ["flow", "respuesta"],
  Jokker: ["punchline", "respuesta"],
  Jaze: ["flow", "ingenio"],
  Nekroos: ["punchline", "doble-tempo"],
  Stick: ["punchline", "puesta-escena"],
  "Valles-T": ["flow", "respuesta"],
  Marithea: ["respuesta", "puesta-escena"],
  Alek: ["flow", "metricas"],
  Arkano: ["ingenio", "puesta-escena"],
  Azuky: ["punchline", "flow"],
  Barón: ["metricas", "punchline"],
  CTZ: ["flow", "doble-tempo"],
  Dani: ["metricas", "ingenio"],
  Drose: ["punchline", "respuesta"],
  Exe: ["flow", "puesta-escena"],
  Filósofo: ["ingenio", "respuesta"],
  KG: ["punchline", "flow"],
  Kodigo: ["doble-tempo", "flow"],
  Lokillo: ["puesta-escena", "ingenio"],
  MP: ["punchline", "respuesta"],
  Mnak: ["punchline", "puesta-escena"],
  "Pepe Grillo": ["punchline", "respuesta"],
};

export const STYLE_SOURCE = {
  name: "Clasificación editorial de estilos v1",
  url: "urn:freestyle-arena:editorial:styles:v1",
};
